# Generated by Django 5.0 on 2024-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciscoBGPconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('remote_ip_address', models.CharField(max_length=100)),
                ('as_number', models.CharField(max_length=100)),
                ('remote_as_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceConfigurationSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('interface_name', models.CharField(max_length=100, null=True)),
                ('vlan_id', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ipconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('vlan_id', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('net_mask', models.CharField(max_length=100)),
                ('vd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='juniperBGPconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('remote_ip_address', models.CharField(max_length=100)),
                ('as_number', models.CharField(max_length=100)),
                ('remote_as_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juniperconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('vlan_id', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('net_mask', models.CharField(max_length=100)),
                ('vd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MikrotikIpconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('vlan_id', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('net_mask', models.CharField(max_length=100)),
                ('vd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendorconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendorforSwitchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VlanConfigurationSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100, null=True)),
                ('vlan_id', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
